apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: aplicacao-pod
      labels:
       name: aplicacao-pod
    spec:
      containers:
        - name: container-aplicacao-loja
          image: aluracliregistry.azurecr.io/loja/aplicacao-loja:v1
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: aluracliregistry.secret
          # imagePullCredentials:
          #   username: name
          #   password: password
  selector:
    matchLabels:
      name: aplicacao-pod